// Vendored copy of @typescript-eslint/visitor-keys's runtime table — the
// union of `eslint-visitor-keys`'s core ESTree keys and the TS-specific
// additions typescript-eslint layers on top. Used by:
//   - the SourceCode constructor (lib/languages/js/source-code/source-code.js)
//     to walk the lazy ESTree.
//   - selector-analysis's :has / sibling / :nth-child helpers, which need
//     the visitor-keys-ordered list of child slots per node type.
//
// Order within each list matters: child slots must appear in the order
// they appear in source code (e.g. ClassDeclaration is `id, superClass,
// body`, not alphabetical). CodePathAnalyzer relies on this ordering for
// `state.makeIfConsequent` / `makeForInOfRight` etc. to fire at the right
// step in the walk.
//
// Keep in sync with @typescript-eslint/visitor-keys when bumping ESLint /
// typescript-eslint major versions. Regenerate via:
//   node -e "const p=require('path');const r=p.dirname(require.resolve('eslint/package.json'));const{visitorKeys}=require(require.resolve('@typescript-eslint/visitor-keys',{paths:[r]}));for (const k of Object.keys(visitorKeys).sort()) console.log(k, visitorKeys[k]);"
export const visitorKeys: Record<string, readonly string[]> = {
	'AccessorProperty': ['decorators', 'key', 'typeAnnotation', 'value'],
	'ArrayExpression': ['elements'],
	'ArrayPattern': ['decorators', 'elements', 'typeAnnotation'],
	'ArrowFunctionExpression': ['typeParameters', 'params', 'returnType', 'body'],
	'AssignmentExpression': ['left', 'right'],
	'AssignmentPattern': ['decorators', 'left', 'right', 'typeAnnotation'],
	'AwaitExpression': ['argument'],
	'BinaryExpression': ['left', 'right'],
	'BlockStatement': ['body'],
	'BreakStatement': ['label'],
	'CallExpression': ['callee', 'typeArguments', 'arguments'],
	'CatchClause': ['param', 'body'],
	'ChainExpression': ['expression'],
	'ClassBody': ['body'],
	'ClassDeclaration': ['decorators', 'id', 'typeParameters', 'superClass', 'superTypeArguments', 'implements', 'body'],
	'ClassExpression': ['decorators', 'id', 'typeParameters', 'superClass', 'superTypeArguments', 'implements', 'body'],
	'ConditionalExpression': ['test', 'consequent', 'alternate'],
	'ContinueStatement': ['label'],
	'DebuggerStatement': [],
	'Decorator': ['expression'],
	'DoWhileStatement': ['body', 'test'],
	'EmptyStatement': [],
	'ExperimentalRestProperty': ['argument'],
	'ExperimentalSpreadProperty': ['argument'],
	'ExportAllDeclaration': ['exported', 'source', 'attributes'],
	'ExportDefaultDeclaration': ['declaration'],
	'ExportNamedDeclaration': ['declaration', 'specifiers', 'source', 'attributes'],
	'ExportSpecifier': ['local', 'exported'],
	'ExpressionStatement': ['expression'],
	'ForInStatement': ['left', 'right', 'body'],
	'ForOfStatement': ['left', 'right', 'body'],
	'ForStatement': ['init', 'test', 'update', 'body'],
	'FunctionDeclaration': ['id', 'typeParameters', 'params', 'returnType', 'body'],
	'FunctionExpression': ['id', 'typeParameters', 'params', 'returnType', 'body'],
	'Identifier': ['decorators', 'typeAnnotation'],
	'IfStatement': ['test', 'consequent', 'alternate'],
	'ImportAttribute': ['key', 'value'],
	'ImportDeclaration': ['specifiers', 'source', 'attributes'],
	'ImportDefaultSpecifier': ['local'],
	'ImportExpression': ['source', 'options'],
	'ImportNamespaceSpecifier': ['local'],
	'ImportSpecifier': ['imported', 'local'],
	'JSXAttribute': ['name', 'value'],
	'JSXClosingElement': ['name'],
	'JSXClosingFragment': [],
	'JSXElement': ['openingElement', 'children', 'closingElement'],
	'JSXEmptyExpression': [],
	'JSXExpressionContainer': ['expression'],
	'JSXFragment': ['openingFragment', 'children', 'closingFragment'],
	'JSXIdentifier': [],
	'JSXMemberExpression': ['object', 'property'],
	'JSXNamespacedName': ['namespace', 'name'],
	'JSXOpeningElement': ['name', 'typeArguments', 'attributes'],
	'JSXOpeningFragment': [],
	'JSXSpreadAttribute': ['argument'],
	'JSXSpreadChild': ['expression'],
	'JSXText': [],
	'LabeledStatement': ['label', 'body'],
	'Literal': [],
	'LogicalExpression': ['left', 'right'],
	'MemberExpression': ['object', 'property'],
	'MetaProperty': ['meta', 'property'],
	'MethodDefinition': ['decorators', 'key', 'value'],
	'NewExpression': ['callee', 'typeArguments', 'arguments'],
	'ObjectExpression': ['properties'],
	'ObjectPattern': ['decorators', 'properties', 'typeAnnotation'],
	'PrivateIdentifier': [],
	'Program': ['body'],
	'Property': ['key', 'value'],
	'PropertyDefinition': ['decorators', 'key', 'typeAnnotation', 'value'],
	'RestElement': ['decorators', 'argument', 'typeAnnotation'],
	'ReturnStatement': ['argument'],
	'SequenceExpression': ['expressions'],
	'SpreadElement': ['argument'],
	'StaticBlock': ['body'],
	'Super': [],
	'SwitchCase': ['test', 'consequent'],
	'SwitchStatement': ['discriminant', 'cases'],
	'TSAbstractAccessorProperty': ['decorators', 'key', 'typeAnnotation'],
	'TSAbstractKeyword': [],
	'TSAbstractMethodDefinition': ['key', 'value'],
	'TSAbstractPropertyDefinition': ['decorators', 'key', 'typeAnnotation'],
	'TSAnyKeyword': [],
	'TSArrayType': ['elementType'],
	'TSAsExpression': ['expression', 'typeAnnotation'],
	'TSAsyncKeyword': [],
	'TSBigIntKeyword': [],
	'TSBooleanKeyword': [],
	'TSCallSignatureDeclaration': ['typeParameters', 'params', 'returnType'],
	'TSClassImplements': ['expression', 'typeArguments'],
	'TSConditionalType': ['checkType', 'extendsType', 'trueType', 'falseType'],
	'TSConstructSignatureDeclaration': ['typeParameters', 'params', 'returnType'],
	'TSConstructorType': ['typeParameters', 'params', 'returnType'],
	'TSDeclareFunction': ['id', 'typeParameters', 'params', 'returnType', 'body'],
	'TSDeclareKeyword': [],
	'TSEmptyBodyFunctionExpression': ['id', 'typeParameters', 'params', 'returnType'],
	'TSEnumBody': ['members'],
	'TSEnumDeclaration': ['id', 'body'],
	'TSEnumMember': ['id', 'initializer'],
	'TSExportAssignment': ['expression'],
	'TSExportKeyword': [],
	'TSExternalModuleReference': ['expression'],
	'TSFunctionType': ['typeParameters', 'params', 'returnType'],
	'TSImportEqualsDeclaration': ['id', 'moduleReference'],
	'TSImportType': ['source', 'options', 'qualifier', 'typeArguments'],
	'TSIndexSignature': ['parameters', 'typeAnnotation'],
	'TSIndexedAccessType': ['objectType', 'indexType'],
	'TSInferType': ['typeParameter'],
	'TSInstantiationExpression': ['expression', 'typeArguments'],
	'TSInterfaceBody': ['body'],
	'TSInterfaceDeclaration': ['id', 'typeParameters', 'extends', 'body'],
	'TSInterfaceHeritage': ['expression', 'typeArguments'],
	'TSIntersectionType': ['types'],
	'TSIntrinsicKeyword': [],
	'TSLiteralType': ['literal'],
	'TSMappedType': ['key', 'constraint', 'nameType', 'typeAnnotation'],
	'TSMethodSignature': ['key', 'typeParameters', 'params', 'returnType'],
	'TSModuleBlock': ['body'],
	'TSModuleDeclaration': ['id', 'body'],
	'TSNamedTupleMember': ['label', 'elementType'],
	'TSNamespaceExportDeclaration': ['id'],
	'TSNeverKeyword': [],
	'TSNonNullExpression': ['expression'],
	'TSNullKeyword': [],
	'TSNumberKeyword': [],
	'TSObjectKeyword': [],
	'TSOptionalType': ['typeAnnotation'],
	'TSParameterProperty': ['decorators', 'parameter'],
	'TSPrivateKeyword': [],
	'TSPropertySignature': ['key', 'typeAnnotation'],
	'TSProtectedKeyword': [],
	'TSPublicKeyword': [],
	'TSQualifiedName': ['left', 'right'],
	'TSReadonlyKeyword': [],
	'TSRestType': ['typeAnnotation'],
	'TSSatisfiesExpression': ['expression', 'typeAnnotation'],
	'TSStaticKeyword': [],
	'TSStringKeyword': [],
	'TSSymbolKeyword': [],
	'TSTemplateLiteralType': ['quasis', 'types'],
	'TSThisType': [],
	'TSTupleType': ['elementTypes'],
	'TSTypeAliasDeclaration': ['id', 'typeParameters', 'typeAnnotation'],
	'TSTypeAnnotation': ['typeAnnotation'],
	'TSTypeAssertion': ['typeAnnotation', 'expression'],
	'TSTypeLiteral': ['members'],
	'TSTypeOperator': ['typeAnnotation'],
	'TSTypeParameter': ['name', 'constraint', 'default'],
	'TSTypeParameterDeclaration': ['params'],
	'TSTypeParameterInstantiation': ['params'],
	'TSTypePredicate': ['parameterName', 'typeAnnotation'],
	'TSTypeQuery': ['exprName', 'typeArguments'],
	'TSTypeReference': ['typeName', 'typeArguments'],
	'TSUndefinedKeyword': [],
	'TSUnionType': ['types'],
	'TSUnknownKeyword': [],
	'TSVoidKeyword': [],
	'TaggedTemplateExpression': ['tag', 'typeArguments', 'quasi'],
	'TemplateElement': [],
	'TemplateLiteral': ['quasis', 'expressions'],
	'ThisExpression': [],
	'ThrowStatement': ['argument'],
	'TryStatement': ['block', 'handler', 'finalizer'],
	'UnaryExpression': ['argument'],
	'UpdateExpression': ['argument'],
	'VariableDeclaration': ['declarations'],
	'VariableDeclarator': ['id', 'init'],
	'WhileStatement': ['test', 'body'],
	'WithStatement': ['object', 'body'],
	'YieldExpression': ['argument'],
};
